spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: jdbc:h2:mem:iptu;MODE=MySQL;
    url: jdbc:mysql://localhost:23306/iptu?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: jojoba
    password: jojoba123
    jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false
          id.new_generator_mappings: true
          show_sql: false
          hbm2ddl.auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jojoba_talk?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: jojoba
    password: jojoba123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        id.new_generator_mappings: true
        show_sql: false
        hbm2ddl.auto: validate
decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: false
logging:
  level:
    org:
      hibernate:
        SQL: info